### ISSUE TITLE
Once sensor is not available, it is killing whole homebridge

### ISSUE THREAD

**Issue by markunca** [oiva/homebridge-air-quality-file#11]
Hi,
once there is problem to use sensor:

```
pi@homebridge-tman:~/air-quality $ sudo python3 aqi_homebridge.py
Traceback (most recent call last):
  File "aqi_homebridge.py", line 7, in <module>
    import sds011
ModuleNotFoundError: No module named 'sds011'
```

 in json is saved None as value which kill homebridge with status:

```
SyntaxError: Unexpected token N in JSON at position 11
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/homebridge-air-quality-file/dist/index.js:198:29
    at /usr/lib/node_modules/homebridge-air-quality-file/dist/index.js:77:12
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by oiva** [comment]
Well that's not good at all. I'll see what I can do.
